name: Setup course infra
on:
  workflow_dispatch:
defaults:
  run:
    working-directory: ./infra
jobs:
  setup-infra:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      TF_VAR_gcp_region: europe-north1
      TF_VAR_gcp_zone: europe-north1-a
      TF_VAR_gcp_project: ${{ secrets.GCP_PROJECTID }}
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # ratchet:step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            checkpoint-api.hashicorp.com:443
            github.com:443
            iamcredentials.googleapis.com:443
            storage.googleapis.com:443
            raw.githubusercontent.com:443
            sts.googleapis.com:443
            api.github.com:443
            objects.githubusercontent.com:443
            registry.opentofu.org:443
            openidconnect.googleapis.com:443

      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
        with:
          persist-credentials: false

      - name: GCP auth
        uses: google-github-actions/auth@71fee32a0bb7e97b4d33d548e7d957010649d8fa # ratchet:google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ secrets.GCP_PROJECTID }}/locations/global/workloadIdentityPools/lf260-pool/providers/github
          service_account: ${{ secrets.GCP_SERVICEUSER }}

      - uses: opentofu/setup-opentofu@ae80d4ecaab946d8f5ff18397fbf6d0686c6d46a # ratchet:opentofu/setup-opentofu@v1

      - run: tofu init
      
      - run: tofu validate
      
      - id: "apply"
        name: Tofu apply
        run: tofu apply -auto-approve -no-color



