name: Setup course env using OpenTofu
on:
  workflow_dispatch:
jobs:
  setup-env:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # ratchet:step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            dl.google.com:443
            github.com:443
            iamcredentials.googleapis.com:443
            raw.githubusercontent.com:443
            storage.googleapis.com:443
            sts.googleapis.com:443
            api.github.com:443
            objects.githubusercontent.com:443

      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
        with:
          persist-credentials: false

      - name: GCP auth
        uses: google-github-actions/auth@71fee32a0bb7e97b4d33d548e7d957010649d8fa # ratchet:google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ secrets.GCP_PROJECTID }}/locations/global/workloadIdentityPools/lf260-pool/providers/github
          service_account: ${{ secrets.GCP_SERVICEUSER }}

      - uses: opentofu/setup-opentofu@ae80d4ecaab946d8f5ff18397fbf6d0686c6d46a # ratchet:opentofu/setup-opentofu@v1

      - run: tofu init
      
      - id: plan
        name: Tofu plan
        run: tofu -chdir=terraform/ plan -no-color
        env:
          TF_VAR_gcp_project: ${{ secrets.GCP_PROJECTID }}
          TF_VAR_gcp_region: europe-north1

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}

